---
# This playbook doesn't support window machine
- name: Configuring machine
  gather_facts: true
  become: "{{ is_privileged }}" # for linux machine we will need this to be true
  hosts: all
  serial: 1

  vars_files:
    - aliases.yml
    - mas.yml
    - general_deps.yml
    - apt_deps.yml
    - brew_deps.yml
    - snap_deps.yml
    - brew_cask.yml

  tasks:
    - name: OS details
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: Exit unsupported OS
      ansible.builtin.meta: end_host
      when:
        - ansible_distribution != "MacOSX"
        - ansible_distribution != "Ubuntu"

    - name: Install general dependencies
      block:
        - name: Update apt packages
          when: ansible_distribution == "Ubuntu"
          ansible.builtin.apt:
            update_cache: true

        - name: Packages installation
          ansible.builtin.package:
            name: "{{ general_dependencies }}"
            state: present

    - name: Install MacOS dependencies
      when: ansible_distribution == "MacOSX"
      block:
        - name: Install OSS using homebrew
          ansible.builtin.package:
            name: "{{ brew_dependencies }}"
            state: present

        - name: Install tools using homebrew_cask
          community.general.homebrew_cask:
            name: "{{ brew_cask_dependencies }}"
            state: present
            accept_external_apps: true
            install_options: "debug"

        # - name: Install applications from AppStore using mas
        #   community.general.mas:
        #     id: "{{ mas_dependencies }}"
        #     state: present

    - name: Install Ubuntu dependencies
      when: ansible_distribution == "Ubuntu"
      block:
        - name: Install APT dependencies
          block:
            - name: Add GPG Key
              ansible.builtin.apt_key:
                url: "{{ item.apt_key }}"
                state: present
              when: item.apt_key is defined
              loop: "{{ apt_dependencies | selectattr('apt_key', 'defined') | list }}"

            - name: Add APT Repository
              ansible.builtin.apt_repository:
                repo: "{{ item.apt_repo }}"
                state: present
                filename: "{{ item.name }}"
              when: item.apt_repo is defined
              loop: "{{ apt_dependencies | selectattr('apt_repo', 'defined') | list }}"

            - name: APT update
              ansible.builtin.apt:
                update_cache: true

            - name: APT install
              ansible.builtin.apt:
                name: "{{ item.name }}"
              loop: "{{ apt_dependencies }}"

            - name: Install Istio
              ansible.builtin.shell: |
                if ! (which istioctl) &> /dev/null; then
                  echo "installing istio";
                  (curl -sL https://istio.io/downloadIstioctl | sh - && export PATH=$HOME/.istioctl/bin:$PATH);
                else
                  echo "istio existed";
                fi;
              args:
                creates: "{{ ansible_facts.user_dir }}/.istioctl"

        - name: Install snap dependencies
          community.general.snap:
            name: "{{ item }}"
            classic: yes # https://snapcraft.io/docs/snap-confinement
            dangerous: false
            channel: stable
          loop: "{{ snap_dependencies }}"

        - name: Create symlink # some snap package bin are not in /snap/bin by default
          ansible.builtin.file:
            src: "{{ item.src }}"
            dest: "/snap/bin/{{ item.name }}"
            state: link
          loop:
            - name: k9s
              src: /snap/k9s/current/bin/k9s
            - name: ansible-lint
              src: /snap/durrendal-ansible-lint/current/bin/ansible-lint

        - name: Install vegeta
          ansible.builtin.shell: |
            cd ~;
            VEGETA_VERSION=$(curl -s "https://api.github.com/repos/tsenart/vegeta/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
            curl -Lo vegeta.tar.gz "https://github.com/tsenart/vegeta/releases/latest/download/vegeta_${VEGETA_VERSION}_linux_amd64.tar.gz"
            mkdir vegeta-temp
            tar xf vegeta.tar.gz -C vegeta-temp
            mv vegeta-temp/vegeta /usr/local/bin
            rm -rf vegeta.tar.gz
            rm -rf vegeta-temp
          args:
            creates: /usr/local/bin/vegeta

        - name: Install Azure CLI
          ansible.builtin.shell: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | bash
          args:
            creates: /usr/bin/az

        - name: Set zsh as the default shell
          ansible.builtin.command: "chsh -s /usr/bin/zsh"

    # Custom install tools
    - name: Custom install general tools
      block:
        - name: Install nvm
          ansible.builtin.shell: |
            if ! (which nvm) &> /dev/null; then
              echo "installing nvm";
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash;
            else
              echo "nvm existed";
            fi;
          args:
            creates: "{{ ansible_facts.user_dir }}/.nvm/nvm.sh"

        - name: Install NodeJS using nvm
          ansible.builtin.shell: |
            . {{ ansible_facts.user_dir }}/.nvm/nvm.sh && nvm install "{{ nodejs_version }}" && nvm use  "{{ nodejs_version }}"
          args:
            executable: /bin/bash
            chdir: "{{ ansible_facts.user_dir }}"
            creates: "{{ ansible_facts.user_dir }}/.nvm/versions/node/v{{ nodejs_version }}"

        - name: Install SDK Man and Java
          ansible.builtin.import_role:
            name: java

        - name: Install AWS CLI
          ansible.builtin.import_role:
            name: aws_cli

        - name: Update shell profile
          ansible.builtin.lineinfile:
            path: "{{ os_var.shell_profile[ansible_distribution] }}"
            line: "{{ item }}"
          loop:
            - "source <(kubectl completion {{ os_var.preferred_shell[ansible_distribution] }})"
            - 'eval "$(direnv hook {{ os_var.preferred_shell[ansible_distribution] }})"'
            - 'source "$HOME/.sdkman/bin/sdkman-init.sh"'

        - name: Ensure alias
          ansible.builtin.lineinfile:
            path: "{{ os_var.shell_profile[ansible_distribution] }}"
            line: "{{ item }}"
          loop: "{{ all_aliases }}"

        - name: Customize vi editor
          ansible.builtin.blockinfile:
            path: ~/.vimrc
            create: true
            marker: '" {mark} ANSIBLE MANAGED BLOCK (VIM SETTINGS)' #using " because it's comment in vi
            block: "{{ lookup('ansible.builtin.file', 'files/vi.cfg') }}"

        - name: ohmyzsh
          block:
            - name: Install ohmyzsh
              ansible.builtin.git:
                repo: "https://github.com/ohmyzsh/ohmyzsh.git"
                dest: "~/.oh-my-zsh"
                version: master

            - name: Install zsh-autosuggestions
              ansible.builtin.git:
                repo: "https://github.com/zsh-users/zsh-autosuggestions"
                dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
                version: master

            - name: Ensure plugin
              ansible.builtin.lineinfile:
                path: "{{ os_var.shell_profile[ansible_distribution] }}"
                regexp: "^plugins="
                line: plugins=(git zsh-autosuggestions docker podman iterm2 nvm safe-paste ssh ssh-agent opentofu thefuck)

            - name: Ensure theme
              ansible.builtin.lineinfile:
                path: "{{ os_var.shell_profile[ansible_distribution] }}"
                regexp: "^ZSH_THEME="
                line: ZSH_THEME="simple"
