---
# This playbook doesn't support window machine
- name: Configuring MacOS machine
  gather_facts: true
  hosts: localhost

  vars_files:
    - aliases.yml
    - mas.yml
    - brew-cask.yml

  vars:
    general_dependencies:
      - ca-certificates
      - kubectl
      - bash-completion
      - kubectx
      - helm
      - git
      - podman
      - liquibase
      - sqlc
      - sysdig
      - jq
      - yq
      - direnv
      - golang-migrate
      - ngrok
      - zip
      - unzip
      - trivy
      - yarn
    brew_dependencies:
      - zsh-completions
      - mas
      - derailed/k9s/k9s
      - vegeta
      - protobuf
      - opentofu
      - pstree
      - zig
      - go
      - gcc
      - ansible-lint
      - azure-cli
      - argocd
    apt_dependencies:
      - gnupg
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - curl
      - gnupg
      - protobuf-compiler
      - psmisc
      - golang-go
      - build-essential

    snap_dependencies:
      - k9s
      - dbeaver-ce
      - opentofu
      - zig
      - aws-cli
      - durrendal-ansible-lint

  tasks:
    - name: OS details
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"

    - name: Exit unsupported OS
      ansible.builtin.meta: end_host
      when:
        - ansible_distribution != "MacOSX"

    - name: Install general dependencies
      ansible.builtin.package:
        name: "{{ general_dependencies }}"
        state: present

    - name: Install MacOS dependencies
      when: ansible_distribution == "MacOSX"
      block:
        - name: Install OSS using homebrew
          ansible.builtin.package:
            name: "{{ brew_dependencies }}"
            state: present

        - name: Install tools using homebrew_cask
          community.general.homebrew_cask:
            name: "{{ brew_cask_dependencies }}"
            state: present
            accept_external_apps: true
            install_options: "debug"

        # - name: Install applications from AppStore using mas
        #   community.general.mas:
        #     id: "{{ mas_dependencies }}"
        #     state: present

    - name: Install Ubuntu dependencies
      when: ansible_distribution == "Ubuntu"
      block:
        - name: Trust GPG key and configure APT repositories
          ansible.builtin.shell: |
            # sysdig
            if ! (which sysdig) &> /dev/null; then
              curl -s https://download.sysdig.com/DRAIOS-GPG-KEY.public | apt-key add -;
              curl -s -o /etc/apt/sources.list.d/draios.list https://download.sysdig.com/stable/deb/draios.list;
            fi;

            # git
            if ! (which git) &> /dev/null; then
              add-apt-repository ppa:git-core/ppa;
              apt-get update;
            fi;

            # yq
            if ! (which yq) &> /dev/null; then
              add-apt-repository ppa:rmescandon/yq;
            fi;

            # golang-migrate
            if ! (which yq) &> /dev/null; then
              curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | bash;
            fi;

            # ngrok
            if ! (which ngrok) &> /dev/null; then
              curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
              | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
              && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
              | tee /etc/apt/sources.list.d/ngrok.list
            fi;

            # trivy
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list

          changed_when: false

        - name: Install APT dependencies
          ansible.builtin.apt:
            update_cache: true
            name: "{{ apt_dependencies }}"

        - name: Install snap dependencies
          community.general.snap:
            name: "{{ snap_dependencies }}"
            classic: yes
            channel: stable

        - name: Install vegeta
          ansible.builtin.shell: |
            cd ~;
            git clone https://github.com/tsenart/vegeta;
            cd vegeta;
            make vegeta;
            mv vegeta ~/bin;
            cd ~;
            rm -rf vegeta;
          args:
            creates: /bin/vegeta

        - name: Install Azure CLI
          ansible.builtin.shell: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | bash
          args:
            creates: hihi #todo replace with the correct path

    # Custom install tools
    - name: Custom install general tools
      block:
        - name: Install Istio
          ansible.builtin.shell: |
            if ! (which istioctl) &> /dev/null; then
              echo "installing istio";
              (curl -sL https://istio.io/downloadIstioctl | sh - && export PATH=$HOME/.istioctl/bin:$PATH);
            else
              echo "istio existed";
            fi;
          register: istio_output
          changed_when: istio_output.stdout != "istio existed"

        - name: Install nvm
          ansible.builtin.shell: |
            if ! (which nvm) &> /dev/null; then
              echo "installing nvm";
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash;
            else
              echo "nvm existed";
            fi;
          args:
            creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

        - name: Install NodeJS using nvm
          ansible.builtin.shell: |
            . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install "{{ nodejs_version }}" && nvm use  "{{ nodejs_version }}"
          args:
            executable: /bin/bash
            chdir: "{{ ansible_env.HOME }}"
            creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ nodejs_version }}"

        - name: Install SDK Man and Java
          ansible.builtin.import_role:
            name: java

        - name: Install AWS CLI
          ansible.builtin.import_role:
            name: aws-cli

        - name: Update shell profile
          ansible.builtin.lineinfile:
            path: "{{ os_var.shell_profile[ansible_distribution] }}"
            line: "{{ item }}"
          loop:
            - "source <(kubectl completion {{ os_var.preferred_shell[ansible_distribution] }})"
            - 'eval "$(direnv hook {{ os_var.preferred_shell[ansible_distribution] }})"'
            - 'source "$HOME/.sdkman/bin/sdkman-init.sh"'

        - name: Ensure alias
          ansible.builtin.lineinfile:
            path: "{{ os_var.shell_profile[ansible_distribution] }}"
            line: "{{ item }}"
          loop: "{{ all_aliases }}"

        - name: Customize vi editor
          ansible.builtin.blockinfile:
            path: ~/.vimrc
            create: true
            marker: '" {mark} ANSIBLE MANAGED BLOCK (VIM SETTINGS)' #using " because it's comment in vi
            block: "{{ lookup('ansible.builtin.file', 'files/vi.cfg') }}"
