all_aliases:
  - export ZSH="$HOME/.oh-my-zsh"
  - alias grep='grep --color=auto'
  - alias ll='ls -al'
  - alias dcp='docker-compose'
  - alias ter='terraform'
  - alias pwsleep='pmset sleepnow'
  - alias mks='minikube'
  - alias k='kubectl'
  - alias mergemain='git fetch origin main:main && git merge main'
  - alias greset='git reset --hard'
  - alias gundo='git reset HEAD~'
  - alias gcurr="git branch | grep '*'"
  - alias gmain='git checkout main && git pull'
  - alias ap='ansible-playbook'
  - alias gitcleanbranches='git branch | xargs -I % echo "git push -d % ; git branch -D %" | zsh'
  - alias wk='watch kubectl'
  - alias gitgrep='git branch | grep '
  - alias py='python3'
  - alias pip='pip3'
  - alias g='gcloud'
  - alias kus='kustomize'
  - alias amendforce='git commit --amend --no-edit && git push --force --force-with-lease'
  - alias allamendforce='git add . && git commit --amend --no-edit && git push --force --force-with-lease'
  - alias amen0edit='git commit --amend --no-edit'
  - alias stopallcontainer='docker ps --format json | jq .ID | xargs -I % docker stop %'
  - export yaml='--dry-run=client -oyaml'
  - export now='--force --grace-period 0'
  - complete -o default -F __start_kubectl k
  - export PAGER="less -F -X"
  - source ~/.nvm/nvm.sh
  - source $ZSH/oh-my-zsh.sh
