- name: Installing SDK Man
  ansible.builtin.shell: set -o pipefail && "curl -s 'https://get.sdkman.io' | bash"
  args:
    creates: "{{ ansible_facts.user_dir }}/.sdkman/bin/sdkman-init.sh"

- name: Installing Java
  ansible.builtin.shell: |
    source "$HOME/.sdkman/bin/sdkman-init.sh" && \
    sdk install java {{ java_version }}
  args:
    executable: /bin/zsh
  changed_when: false

- name: Installing Gradle
  ansible.builtin.shell: |
    source "$HOME/.sdkman/bin/sdkman-init.sh" && \
    sdk install gradle {{ gradle_version }}
  changed_when: false
